plugins {
    id 'com.android.application'
}

android {
   // compileSdkVersion 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    def versionPropsFile = file('version.properties')

    if (versionPropsFile.canRead()) {
        Properties versionProps = new Properties()

        versionProps.load(new FileInputStream(versionPropsFile))
        def name = versionProps['VERSION_NAME']
        def code = versionProps['VERSION_CODE'].toInteger() + 1
        versionProps['VERSION_CODE'] = code.toString()
        versionProps.store(versionPropsFile.newWriter(), null)

            defaultConfig {
            applicationId "io.github.rlshep.bjcp2015beerstyles"
            versionName name
            versionCode code
            minSdkVersion 23
            targetSdkVersion 35
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
    } else {
        throw new Exception("Could not read version.properties!")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

    configurations.configureEach {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }
    defaultConfig {
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner = 'androidx.test.runner.AndroidJUnitRunner'
        compileSdk 35
    }
    namespace 'io.github.rlshep.bjcp2015beerstyles'
}

dependencies {
    implementation 'io.github.rlshep:BJCPBeerStyles_Core:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'commons-lang:commons-lang:2.6'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
//    implementation 'com.appyvet:materialrangebar:1.4.6'
    implementation files('libs/materialrangebar-1.4.6.aar')
    implementation 'com.android.support:cardview-v7'
    implementation 'com.google.guava:guava:27.0.1-android'

    // App's dependencies, including test
    implementation 'androidx.annotation:annotation:1.9.1'

    implementation 'androidx.vectordrawable:vectordrawable:1.2.0'
    implementation 'androidx.test:runner:1.6.2'
    testImplementation 'junit:junit:4.12'

    // Testing-only dependencies
    testImplementation 'org.mockito:mockito-core:2.25.1'
    androidTestImplementation 'org.mockito:mockito-android:2.25.1'

    androidTestImplementation 'androidx.test:rules:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.3.2'
}